### PR TITLE
WIP: Bp/549/update plugin editions

### PR DESCRIPTION
**Pull request by bhupeshappfoster**
### Description:
[Provide a brief description of the purpose and goal of this pull request.]

### Related Issue(s):

- [#549](https://github.com/AcclaroInc/pm-craft-translations/issues/549)

### Changes Made:
[List the changes made in this pull request to address the issue or implement the feature.]

**Added:**

- 

**Changed:**

-

**Deprecated:**

-

**Removed:**

-

**Fixed:**

-

**Security:**

-

### Testing:
[Describe the testing performed to ensure the changes are functioning as expected.]

- 

### Quality Assurance (QA):

- [ ] The code has been reviewed and approved by the QA team.
- [ ] The changes have been tested on different environments (e.g., staging, production).
- [ ] Integration tests have been performed to verify the interactions between components.
- [ ] Performance tests have been conducted to ensure the changes do not impact system performance.
- [ ] Any necessary database migrations or data transformations have been executed successfully.
- [ ] Accessibility requirements have been considered and tested (e.g., screen reader compatibility, keyboard navigation).

### Resources:

**Screenshots (if applicable):**
[Include any relevant screenshots to visually demonstrate the changes.]

### Wrapping up

**Checklist:**

- [ ] The code builds without any errors or warnings.
- [ ] The code follows the project's coding conventions and style guidelines.
- [ ] Unit tests have been added or updated to cover the changes made.
- [ ] The documentation has been updated to reflect the changes (if applicable).
- [ ] All new and existing tests pass successfully.
- [ ] The PR has been reviewed by at least one other team member.

**Additional Notes:**
[Include any additional notes, considerations, or context that may be relevant.]

### CODE REVIEW

**Comment by MerrittBoydston** [comment]
## 🆕 Updates
- @sidedwards - do we need to wait for Michael's feedback on plugin editions before merging this?
- @bhupeshappfoster  did we make changes on the console on top of the CMS?

**Comment by bhupeshappfoster** [comment]
> @bhupeshappfoster did we make changes on the console on top of the CMS?

@MerrittBoydston Not clear to me can you please explain what is this about.

**Comment by bhupeshappfoster** [comment]
> ## 🆕 Updates
> * @sidedwards - do we need to wait for Michael's feedback on plugin editions before merging this?
> * @bhupeshappfoster  did we make changes to the console of CMS?

@MerrittBoydston No i did not, as making any changes in console is going to impact current pricing strategy for even craft4 version. Waiting for @sidedwards on this one to confirm how to go ahead.

**Comment by bhupeshappfoster** [comment]
### :new: Updates

**Closing the PR as changes not planner and will be reducing the pricing of plugin to $99 when craft 5 release is made.**

**Pull request closed without merging**
