### PR TITLE
Due date sync and display feature

### PR DESCRIPTION
**Pull request by shnsumit**
- [ ] https://github.com/AcclaroInc/pm-craft-translations/issues/120

### CODE REVIEW

**Comment by sidedwards** [comment]
Let's update it so if, on order sync, the 'Requested Due Date' no longer matches the 'Due Date', display a row called "Order Due Date" that displays the value.

**Comment by shnsumit** [comment]
@sidedwards  PR updated, you can review the PR when get time.

**Comment by sidedwards** [comment]
@shnsumit this update triggered an error on acclarocraft3.com.

image

**Comment by shnsumit** [comment]
@sidedwards Looks migration was not run, although I have updated the schema version.

image

**Pull request merged**
