### PR TITLE
#552: dedicated services page for marketing strategy

### PR DESCRIPTION
**Pull request by sharmarishabh1**
### Description:

Adding a dedicated page for services listing. 

### Related Issue(s):
 - [ ] [Create Dedicated Services Page #552](https://github.com/AcclaroInc/pm-craft-translations/issues/552)
 - [ ] [Craft 5 Marketing Strategy #548](https://github.com/AcclaroInc/pm-craft-translations/issues/548)

### Changes Made:
 
  Added a dedicated page for services pages

### Quality Assurance (QA):

- [ ] The code has been reviewed and approved by the QA team.
- [ ] The changes have been tested on different environments (e.g., staging, production).
- [ ] Integration tests have been performed to verify the interactions between components.
- [ ] Performance tests have been conducted to ensure the changes do not impact system performance.
- [ ] Any necessary database migrations or data transformations have been executed successfully.
- [ ] Accessibility requirements have been considered and tested (e.g., screen reader compatibility, keyboard navigation).

### Resources:

**Screenshots**

image

### Wrapping up

**Checklist:**

- [ ] The code builds without any errors or warnings.
- [ ] The code follows the project's coding conventions and style guidelines.
- [ ] Unit tests have been added or updated to cover the changes made.
- [ ] The documentation has been updated to reflect the changes (if applicable).
- [ ] All new and existing tests pass successfully.
- [ ] The PR has been reviewed by at least one other team member.

**Additional Notes:**

The links/buttons showing here need to be worked up - we would need to add those links for it to function properly.

### CODE REVIEW

**Review by sidedwards — CHANGES_REQUESTED** [review]
@sharmarishabh1 can you please update the CTA button text for Technical Support to "Request Support"

I'll work on getting you CTA links.

**Comment by bhupeshappfoster** [comment]
@sharmarishabh1 Please let me know if this is ready to be merged.

**Comment by sharmarishabh1** [comment]
Hi @bhupeshappfoster 
We will be keeping this on hold till the time we can get a final review and CTA links from @sidedwards on the same. 

The things are in process as per the last update shared by @MerrittBoydston 

Thanks!

**Comment by sharmarishabh1** [comment]
Hi @bhupeshappfoster 
I have moved the content of the services page to constants for better scalability and also went forward to add the CTA links. 
Please check for the same and LMK if you need anything more on this. 

PS: I found a better link for "get a quote" and used that than the one we discussed, please check for the same too.

Thanks!

cc @sidedwards @MerrittBoydston

**Pull request merged**
